version: "3.9"
services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      API_TOKEN: ${API_TOKEN}
      KAI_TOKEN: ${KAI_TOKEN}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: